<?php

if (!defined("_VALID_PHP")) {die();}

return [
	// common

	'az' => 'Азербайджанська',
	'en' => 'Англійська',
	'ru' => 'Російська',
	'ua' => 'Українська',

	'access' => 'Доступ',
	'access_granted' => 'Дозволено',
	'access_prohibited' => 'Заборонено',
	'add' => 'Додати',
	'alert' => 'Увага!',
	'alert_success' => 'Чудово!',
	'alert_warning' => 'Увага!',
	'alert_info' => 'Господині на замітку!',
	// 'alert_danger' => 'Дідька лисого!',
	'alert_danger' => 'От халепа!',
	'apply' => 'Застосувати',
	'author' => 'Автор',
	'back' => 'Взад',
	'cancel' => 'Скасувати',
	'common_data' => 'Опис',
	'content' => 'Контент',
	'controls' => 'Керування',
	'del_suc' => 'Успішно видалено',
	'del_err' => 'Помилка видалення',
	'delete' => 'Видалити',
	'delete_confirmation' => 'Ви впевнені, що хочете видалити цей запис?',
	'delete_confirmation_user' => 'Ви впевнені, що хочете видалити цього користувача?',
	'edit' => 'Редагувати',
	'editor' => 'Редактор',
	'filter' => 'Фільтр',
	'filter_all' => 'Усі',
	'filter_popup_title' => 'Додаткові параметри',
	'filter_no_matter' => 'Не важливо',
	'get_err' => 'Неправильні параметри скрипту',
	'greetings' => 'Вітаємо, ',
	'greetings_content' => 'Ласкаво просимо до Irry CMS.<br /><br />Виберіть розділ.',
    'helloAdmin' => 'Вітаємо',
	'image' => 'Зображення',
	'insert_err' => 'Не вдалося додати дані',
	'insert_suc' => 'Успішно додано',
	'logout' => 'Вихід',
	'lookAtSite' => 'На сайт',
	'main_page' => 'Головна',
	'more_info' => 'Докладніше',
	'no_data_found' => 'Даних не знайдено',
	'pg' => 'посторінкове виведення даних',
	'pg_all' => 'показати усі',
	'pg_2end' => 'у кінець',
	'pg_2start' => 'у початок',
	'pg_next' => 'наступна',
	'pg_prev' => 'попередня',
	'publish' => 'Опублікувати',
	'publish_lang' => 'опублікувати цією мовою','publish_off' => 'Не опубліковано',
	'publish_on' => 'Опубліковано',
	'reset' => 'Скасувати зміни',
	'resourses' => 'Ресурси',
	'save' => 'Зберегти',
	'search' => 'Пошук',
	'search_query' => 'введіть пошуковий запит',
	'select' => 'Обрати',
	'show_site' => 'Показати сайт',
	'status' => 'Статус',
	'toggle_navigation' => 'Приховати/показати меню',
	'update_err' => 'Не вдалося зберегти зміни',
	'update_no_data_affected' => 'Змін не було',
	'update_suc' => 'Дані успішно змінені',
	'view' => 'Перегляд',

	// Units

	'y' => 'років',
	'mn' => 'місяців',
	'w' => 'тижнів',
	'd' => 'днів',
	'h' => 'годин',
	'm' => 'хвилин',
	's' => 'секунд',

	// Password Generator

	'password_generator' => 'Генератор пароля',
	'password_generator_approve' => 'Я скопіював пароль у безпечне місце.',
	'password_generator_btn_cancel' => 'Скасування',
	'password_generator_btn_regenerate' => 'Згенерувати ще раз',
	'password_generator_btn_use' => 'Використовувати цей',

	// javascript

	'js_alert' => 'Сповіщення',
	'js_confirmation' => 'Підтвердіть свою дію',
	'js_close' => 'Закрити',
	'js_ok' => 'OK',
	'js_cancel' => 'Скасувати',
	'js_confirm' => 'Підтвердити',

	// File Upload

	'upl_invalid_image_extension_err' => 'Дозволено завантаження файлів тільки з розширеннями *.jpg, *.png',
	'upl_ini_size_err' => 'Загальний обсяг даних перевищив обмеження на сервері',
	'upl_form_size_err' => 'Перевищено допустимий розмір файлу',
	'upl_partial_err' => 'Завантаження було перервано, повторіть спробу',
	'upl_no_file_err' => 'Файл не вибраний',
	'upl_no_tmp_dir_err' => 'Файл не вдалося завантажити через помилку на сервері',
	'upl_can_write_err' => 'Файл не вдалося завантажити через помилку на сервері',
	'upl_extension_err' => 'Файл не вдалося завантажити через помилку на сервері',
	'browse_placeholder' => 'Файл не вибраний',
	'browse_button_text' => 'Огляд',

	// Notification E-mails & messages

	'password_recovery_subj' => 'Відновлення пароля',
	'password_recovery_msg' => '<h1>Доброго дня {username}</h1><p>Для того, щоб змінити пароль, перейдіть за посиланням <a href="{recovery_link}">{recovery_link}</a></p>',

	// CMS - Log in

	'login_title' => 'Вхід до адмін-панелі',
	'login_form_tip' => 'Вхід до адмін-панелі',
	'login_email_placeholder' => 'Пошта',
	'login_password_placeholder' => 'Пароль',
	'login_password_recovery' => 'Відновити пароль',
	'login_remember_me' => 'Запамʼятати мене',
	'login_sign_in' => 'Увійти',
	'login_social_facebook' => 'Увійти за допомогою Facebook',
	'login_social_googleplus' => 'Увійти за допомогою Google+',
	'login_err' => 'Невірний логін або пароль',
	'login_cooldown_err' => 'Забагато спроб входу. Можливість входу користувача тимчасово вимкнена. Спробуйте ще раз незабаром.',
	'login_err_blocked' => 'Цей обліковий запис заблоковано',
	'login_social_err' => 'Для цього користувача ({usermail}, {username}) не зареєстрований обліковий запис',
	'login_suc' => 'Ласкаво просимо',

	// CMS - Password recovery

	'password_recovery_title' => 'Відновлення доступу',
	'password_recovery_email_placeholder' => 'Пошта',
	'password_recovery_form_tip' => 'Будь ласка, введіть свою електронну адресу. На нього буде відправлено посилання на сторінку скидання пароля.',
	'password_recovery_login' => 'Або спробуйте увійти під іншим логіном',
	'password_recovery_err_email_invalid' => 'Введіть валідну адресу поштової скриньки',
	'password_recovery_err_email_cannot_send' => 'Не вдалося відправити лист',
	'password_recovery_err_user_not_found' => 'Такий користувач не зареєстрований',
	'password_recovery_suc_email_sended' => 'Лист був успішно надісланий на вашу адресу {email}. Перевірте папки Вхідні та Спам.',

	// CMS - Password change

	'password_change_title' => 'Зміна пароля',
	'password_change_placeholder' => 'Введіть новий пароль',
	'password_change_err_account_hash_expired' => 'Ви скористалися застарілим посиланням',
	'password_change_suc' => 'Пароль успішно збережено',

	// CMS - Action approve (screenlock)

	'password_approve_title' => 'Перевірка безпеки',
	'password_approve_placeholder' => 'Пароль',
	'password_approve_descr' => 'Ви збираєтеся зробити небезпечну дію. Щоб продовжити, введіть свій пароль.',

	// 403

	'403_title' => '403',
	'403_headline' => 'Доступ заборонено',
	'403_descr' => 'Вам не надано доступ до запитуваної сторінки. Зверніться до адміністратора або <a href="?controller=base&amp;action=sign_out">змініть користувача</a>.',

	// 404

	'404_title' => '404',
	'404_headline' => 'Ой! Сторінку не знайдено.',
	'404_descr' => 'Ми не змогли знайти ту сторінку, яка вам потрібна :( <!-- Meanwhile, you may <a href="{dashboard_link}">відновити до dashboard</a> or try using the search form. - ->',

	// CMS menu blocks and items

	'menu_title' => 'Меню',
	'menu_block_dashboard' => 'Консоль',
	'menu_item_statistics_dashboard' => 'Огляд',
	'menu_block_site_users' => 'Модерація',
	'menu_item_site_users_list' => 'Користувачі',
	'menu_item_site_users_view_info' => 'Особисті дані користувача',
	'menu_item_comments_list' => 'Коментарі',
	'menu_item_comments_edit' => 'Модерувати коментар',
	'menu_block_cms_users' => 'Адміністратори',
	'menu_item_cms_users_list' => 'Користувачі',
	'menu_item_cms_users_add' => 'Додати користувача',
	'menu_item_cms_users_edit' => 'Редагувати користувача',
	'menu_block_content' => 'Контент',
	'menu_block_nav' => 'Навігація',
	'menu_item_articles_list' => 'Публікації',
	'menu_item_articles_add' => 'Додавання публікації',
	'menu_item_articles_edit' => 'Редагувати публікацію',
	'menu_item_gallery_list' => 'Альбоми',
	'menu_item_gallery_add' => 'Додати альбом',
	'menu_item_gallery_edit' => 'Редагувати альбом',
	'menu_item_gallery_photos' => 'Зображення',
	'menu_item_gallery_add_photo' => 'Додати зображення до альбому',
	'menu_item_gallery_edit_photo' => 'Редагувати зображення',
	'menu_item_complaints' => 'Зворотний звʼязок',
	'menu_item_edit_admin_user_cats' => 'Розділи у віданні користувача',
	'menu_item_edit_admin_user_privilegies' => 'Привілеї користувача',
	'menu_block_settings' => 'Налаштування сайту',
	'menu_item_site_languages' => 'Мовні версії',
	'menu_item_edit_lang' => 'Редагувати переклади в мовному файлі',
	'menu_block_subdomains' => 'Субдомени',
	'menu_item_subdomains_list' => 'Субдомени',

	// Dashboard

	'dashboard_latest_members' => 'Останні, що зареєструвалися',
	'dashboard_new_members' => '{n} нов{ua:u1} користувач{ua:u2}',
	'dashboard_view_all_users' => 'Переглянути всіх користувачів',
	'dashboard_articles_posted' => 'публікаці{ua:u1} занесен{ua:u2}',
	'dashboard_cms_users_count' => 'користувач{ua:u1} CMS',

	// CMS users

	'add_cms_user' => 'Додати користувача',
	'cms_user_empty_login_err' => 'Логін не вказано',
	'cms_user_edit_login_invalid_err' => 'Логін має неправильний формат',
	'cms_user_duplicate_login_err' => 'Такий логін вже зареєстрований',
	'cms_user_lang' => 'Мова інтерфейсу',
	'cms_user_lang_placeholder' => 'Виберіть мову',
	'cms_user_lang_err' => 'Введена вами мова відсутня в системі',
	'cms_user_login' => 'Логін (адреса електронної пошти)',
	'cms_user_name' => 'Імʼя',
	'cms_user_name_err' => 'Імʼя користувача неправильне або містить заборонені символи',
	'cms_user_new_pwd' => 'Новий пароль. Щоб не вносити зміни, залиште поле порожнім.',
	'cms_user_not_found' => 'Користувач не знайдено',
	'cms_user_avatar' => 'Аватар',
	'cms_user_pwd' => 'Пароль',
	'cms_user_pwd_generate' => 'Сгенерувати',
	'cms_user_pwd_approve' => 'З метою безпеки введіть свій власний пароль',
	'cms_user_pwd_approve_err' => 'Неправильно вказано пароль. Залишилось %d спроб.',
	'cms_user_pwd_approve_self' => 'Старий пароль',
	'cms_user_pwd_repeat' => 'Підтвердіть пароль',
	'cms_user_pwd_err' => 'Введений вами пароль неправильної довжини або має заборонені символи. Пароль може складатися з 6-64 цифр, літер і розділових знаків.',
	'cms_user_pwd_not_equal_err' => 'Паролі не збігаються',
	'cms_user_reg_date' => 'Дата реєстрації',
	'cms_user_role' => 'Роль',
	'cms_users_role_admin' => 'Адміністратор',
	'cms_users_role_editor' => 'Редактор',
	'cms_user_role_placeholder' => 'Виберіть роль',
	'cms_user_role_err' => 'Роль введена неправильно',
	'cms_user_edit_err_not_found' => 'Користувач не знайдено',
	'cms_user_edit_approvable_data_lost_err' => 'Упс, здається дані загубилися :(',
	'cms_user_is_online' => 'Онлайн',
	'cms_users_list' => 'Список користувачів',
	'cms_users_list_details' => 'Знайден{ua:u1} {count} користувач{ua:u2}',
	'cms_users_search' => 'Пошук користувачів',
	//'cms_users_top_menu_item' => 'Адміністрація',
	'edit_cms_user' => 'Редагувати користувача',
	'edit_cms_user_self' => 'Мій профіль',
	'cms_users_menu_section_allow' => 'Дозволити додавання та редагування контенту в цьому розділі',

	// Photo Gallery

	'gallery' => 'Галерея',
	'gallery_list_details' => '{count} галере{ua:u1} знайден{ua:u2}',
	'gallery_album_add' => 'Додати альбом',
	'gallery_album_add_datetime' => 'Дата додавання',
	'gallery_album_edit' => 'Редагувати альбом',
	'gallery_album_name' => 'Назва альбому',
	'gallery_albums_list' => 'Список альбомів',
	'gallery_name_empty' => 'Назва альбому не може бути порожньою',
	'gallery_not_found_err' => 'Галерея не знайдена',
	'gallery_photo' => 'Малюнок',
	'gallery_photo_add' => 'ще одну',
	'gallery_photo_add_quantity_err' => 'Не можна завантажувати більше 20 картинок',
	'gallery_photo_edit' => 'Редагувати зображення',
	'gallery_photo_name' => 'Назва картинки',
	'gallery_photo_subtext' => 'Підпис до зображення',
	'gallery_photos_add' => 'Додати зображення',
	'gallery_photos_list' => 'Список картинок',
	'gallery_photos_list_details' => '{count} зображен{ua:u1} знайден{ua:u2}',
	'gallery_photos_num' => 'Кількість картинок',
	'gallery_edit_err_name_empty' => 'Назва альбому не може бути порожньою',

	// languages - SITE languages

	'site_lang_code' => 'ISO 639-1',
	'site_lang_name' => 'Самоназва мови',
	'site_lang_published' => 'Опубліковано',
	'site_lang_add_popup_title' => 'Додати на сайт нову мовну версію',
	'site_lang_add_popup_descr' => 'Після додавання нової мовної версії ви зможете перекласти фрази та оповіщення сайту. <strong>Не публікуйте</strong> мовну версію поки не переконайтеся, що всі фрази і хоча б основні пункти меню перекладені. Також необхідно врахувати, що при переході на мовну версію статті, для якої немає перекладу, буде показано 404 помилку.',
	'site_lang_add_err_invalid_code' => 'ISO 639-1 код введено неправильно',
	'site_lang_add_err_duplicate_code' => 'Введений код ISO 639-1 вже зареєстрований',
	'site_lang_add_err_invalid_name' => 'Введіть самоназву мови',
	'site_lang_tr_key' => 'Ключ',
	'site_lang_tr_value' => 'Переклад',
	'site_lang_tr_value_not_translated' => 'Не перекладено',

	// Content - Articles

	'article_category' => 'Категорія',
	'article_category_none' => 'Без категорії',
	'article_sef' => 'ЛЗУ / SEF (людино-зрозуміла URL)',
	'article_sef_descr' => 'Рекомендується вводити переклад заголовка статті англійською мовою.<br />Текст буде перетворено до формату, придатного для URL автоматично.',
	'article_source' => 'Оригінал публікації',
	'article_source_url' => 'Посилання',
	'article_source_name' => 'Назва ресурсу',
	'article_image_descr' => 'Дозволено завантаження файлів {types} типів.',
	'article_image_original_view' => 'Оригінал',
	'article_image_original_size' => 'Розмір оригіналу',
	'article_image_original_upload_datetime' => 'Завантажено на сервер',
	'article_image_thumbnail_size' => 'Розмір ескізу',
	'articles_list_details' => 'Знайден{ua:u1} {count} публікаці{ua:u2}',
	'article_publish_datetime' => 'Дата та час, коли стаття буде опублікована',
	'article_publish_date_placeholder' => 'Дата',
	'article_publish_hour_placeholder' => 'Годинник',
	'article_publish_minutes_placeholder' => 'Хвилини',
	'article_gallery' => 'Галерея',
	'article_author' => 'Творець',
	'article_title' => 'Заголовок',
	'article_keywords' => 'Ключові слова',
	'article_short' => 'Короткий текст',
	'article_full' => 'Текст',
	'article_show_on_main_page' => 'Відображати на головній сторінці',
	'article_show_on_main_page_filter' => 'Показувані на головній',
	'article_show_off_main_page_filter' => 'Не показані на головній',
	'article_is_highlighted' => 'Вибране',
	'article_is_highlighted_filter' => 'Вибрані',
	'article_add_err_title_empty' => 'Заголовок не повинен бути порожнім',
	'article_add_err_full_empty' => 'Текст публікації не повинен бути порожнім',
	'article_add_err_publish_date_invalid' => 'Дата публікації введена неправильно',
	'article_add_err_publish_hour_invalid' => 'Година часу публікації неправильна',
	'article_add_err_publish_minutes_invalid' => 'Хвилини часу публікації вказані неправильно',
	'article_add_err_gallery_not_exists' => 'Галерея не знайдена',
	'article_add_err_source_url_invalid' => 'URL оригіналу не введено',
	'article_edit_err_not_found' => 'Публікація не знайдена',
	'article_edit_err_sef_empty' => 'ЛЗУ публікації не може бути порожнім',
	'articles_assignment' => 'Додат. привʼязка',

	// Navigation

	'nav_menu' => 'Меню',
	'nav_menu_structure' => 'Структура меню',
	'nav_menu_add_item' => 'Додати вкладений елемент',
	'nav_menu_del_item' => 'Видалити вибраний елемент',
	'nav_menu_edit_item' => 'Перегляд / Редагування елемента',
	'nav_menu_item_name' => 'Назва',
	'nav_menu_item_type' => 'Тип',
	'nav_menu_item_type_article' => 'Публікація',
	'nav_menu_item_type_category' => 'Категорія',
	'nav_menu_item_type_spec' => 'Спецсторінка',
	'nav_menu_item_type_url' => 'Посилання',
	'nav_menu_item_sef' => 'ЛЗУ (має бути унікальним)',
	'nav_menu_item_ref_article' => 'Виберіть публікацію (автозаповнення з двох символів)',
	'nav_menu_item_url' => 'URL',
	'nav_menu_item_url_descr' => 'Якщо елемент використовується тільки для створення підменю і не має власної сторінки, залиште символ &laquo;#&raquo;.<br />
	Якщо URL-адреса є локальною для цього сайту, адреса повинна починатися з &laquo;/&raquo;.<br />
	Всі інші адреси будуть трактуватися як глобальні та залишаться без змін.<br />
	Також допустимо використання вайлдкарда {lang} для динамічної вказівки на адресу мовної версії.',
	'nav_menu_item_position' => 'Позиція',
	'nav_menu_item_is_section' => 'Розділ (категорія або спецсторінка, що містить контент та має можливість призначення редактору для заповнення)',
	'nav_menu_add_item_err_type_invalid' => 'Тип вказано неправильно',
	'nav_menu_add_item_err_sef_invalid' => 'ЛЗУ вказано неправильно',
	'nav_menu_add_item_err_sef_exists' => 'Вказаний ЛЗУ вже використаний',
	'nav_menu_add_item_err_article_id_empty' => 'Не вибрано публікацію',
	'nav_menu_add_item_err_article_id_not_exists' => 'Зазначеної публікації не існує',
	'nav_menu_add_item_err_article_id_item_exists' => 'Зазначена публікація вже була використана в меню',
	'nav_menu_add_item_err_name_empty' => 'Введіть назву',
	'nav_menu_add_item_err_position_empty' => 'Жодної позиції не вибрано',
	'nav_menu_edit_item_err_not_found' => 'Елемент не знайдено',
	'nav_menu_level_up' => 'Вгору',

	// Moderation - Site users

	'site_users_list_details' => 'Знайден{ua:u1} {count} користувачів{ua:u2}',
	'site_users_has_registered' => 'користувач{ua:u1} зареєстр{ua:u2}',
	'site_user_profile_info' => 'Профіль',
	'site_user_email' => 'E-mail',
	'site_user_name' => 'Імʼя, прізвище',
	'site_user_reg_date' => 'Дата реєстрації',
	'site_user_reg_date_since' => 'з',
	'site_user_reg_date_till' => 'по',
	'site_users_provider' => 'Провайдер',
	'site_users_provider_none' => 'Самостійний користувач',
	'site_user_nickname' => 'Нік',
	'site_user_birth_date' => 'Дата народження',
	'site_user_gender' => 'Пол',
	'site_user_gender_male' => 'Чоловічий',
	'site_user_gender_female' => 'Жіночий',
	'site_user_registration_datetime' => 'Дата реєстрації',
	'site_user_last_login_datetime' => 'Дата останнього входу',
	'site_user_comments_count' => 'Залишено коментарів',

	// Moderation - Comments

	'comments_list_details' => 'Знайдено {count} коментар{ua:u1}',
	'comments_are_left' => 'коментар{ua:u1} залишено',
	'comments_user' => 'Користувач',
	'comments_preambula' => 'Текст',
	'comment_text' => 'Текст',
	'comments_posted_datetime' => 'Дата',
	'comments_posted_datetime_since' => 'з',
	'comments_posted_datetime_till' => 'по',
	'comments_is_published' => 'Опубліковано',
	'comments_is_inspected' => 'Переглянуто',
	'comment_inspected' => 'Переглянуто',
	'comment_not_inspected' => 'Не переглянуто',
	'comments_moderate' => 'Модерація',
	'comments_moderate_allow' => 'Допустити',
	'comments_moderate_deny' => 'Заборонити',

	// Moderation - Feedback

	'complaints_chat_list' => 'Листування',
	'complaints_username' => 'Імʼя користувача',
	'complaints_last_msg_date' => 'Дата останнього повідомлення',
	'complaints_last_msg_short' => 'Витримка з останнього повідомлення',
	'complaints_answeredness' => 'Відповідь',
	'complaints_answeredness_all' => 'Всі',
	'complaints_answeredness_not' => 'Нема',
	'complaints_answeredness_yep' => 'Є',
	'complaints_answer_notification_sms' => 'Ваше звернення було розглянуте',
	'complaints_answer_notification_subj' => 'Ваше звернення було розглянуте',
	'complaints_answer_notification_email' => '<h1 style="font-size: medium; font-family: serif; font-weight: normal;">Шановний {username},</h1><p style="font-size: medium ; font-family: serif; розглянуто:</p><blockquote>{answer}</blockquote><p style="font-size: medium; font-family: serif; font-weight: normal;">Текст звернення:</p><blockquote > {complaint} </blockquote>',
	'complaints_message_err' => 'Введіть текст',
	'complaints_file_err' => 'Неправильний формат файлу',
	'complaints_chat_with' => 'Листування з користувачем {username}',
	'complaints_answered' => 'Звернення успішно відповідати',
	'complaints_give_answer' => 'Відповісти',

	// Subdomains

	'subdomains_list_details' => '{count} субдомен{ua:u1} у наявності',
	'activate_subdomain_confirmation' => 'Ви впевнені, що хочете перевести адмін-панель у режим редагування контенту вибраного субдомену?',
	'activate_subdomain' => 'Активація субдомену',
	'activate_subdomain_suc' => 'Піддомен був успішно активований',
	'activate_subdomain_err' => 'Неможливо активувати вибраний піддомен',
	'subdomain_not_selected_err' => 'Субдомен не обраний',

];

?>